### ISSUE TITLE
ucompress as global dep

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/ucompress#3]
If you globally install `ucompress`, then you cannot require it, at least with git bash on Windows.
This is a nuance for any global package, not only `ucompress`.

To fix it : `export NODE_PATH=$APPDATA/npm/node_modules`

```
$ npm i -g ucompress
[cut]
+ ucompress@0.14.6
updated 1 package in 19.948s
$ node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> const ucompress = require('ucompress');
Uncaught Error: Cannot find module 'ucompress'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
>
(To exit, press ^C again or ^D or type .exit)
>
$ npm ls -g ucompress
C:\Users\[cut]\AppData\Roaming\npm
`-- ucompress@0.14.6

$ export NODE_PATH=$APPDATA/npm/node_modules
$ node
Welcome to Node.js v12.16.3.
Type ".help" for more information.
> const ucompress = require('ucompress');
undefined
>
```

Just a reminder for casual developer as me, when you read README section `As binary file`, you use the command line and then you want using the dep for a quick snippet.

**Comment by WebReflection** [comment]
wouldn't `npx ucompress --help`, as example, just work? or wouldn't it work without `npx`, if installed globally? In any case, this looks like a bug for node, not for ucompress, as ucompress doesn't really do anything specific on Windows, except trying to use the awkward file path resolution that is incompatible with the Web (sigh).

**Comment by albertosantini** [comment]
Basically all works as expected.

Only I forgot NodeJS global modules nuances.
